# Generated by Django 3.2.9 on 2021-12-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('new_people', models.IntegerField(default=0)),
                ('no_new_days', models.IntegerField(default=0)),
            ],
        ),
    ]
